apiVersion: apps/v1
kind: Deployment
metadata:
  name: qotd
  labels:
    app: qotd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qotd
  template:
    metadata:
      labels:
        app: qotd
    spec:
      containers:
      - name: qotd
        image: moficodes/python-quotes:v1.0.0
        ports:
        - containerPort: 8080
